name: Send Slack notification if workflow fails
description: Send Slack notification if workflow fails

inputs:
  slack_channel_id:
    description: Slack channel ID
    required: true
  webhook_url:
    description: Slack Webhook URL
    required: true
  message:
    description: The message to send to Slack
    default: The last '${{ github.workflow }}' run failed. See ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    required: false
  color:
    description: The color of the Slack message
    default: failure
    required: false

runs:
  using: composite
  steps:
    - name: Send Slack notification if workflow fails
      uses: someimportantcompany/github-actions-slack-message@v1
      with:
        channel: ${{ inputs.slack_channel_id }}
        webhook-url: ${{ inputs.webhook_url }}
        color: ${{ inputs.color }}
        text: ${{ inputs.message }}
