name: Backport pushed commit for production
on:
  push:
    branches:
      - production
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  backport_to_master:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        gh pr create --base master --title "[backport] backport to master"

        # 後続のステップで利用するため作成した PR の number を取得し環境変数に入れる
        # branch を元に URL を取得しそれを正規表現で number のみ抽出している
        echo "TARGET_PR_NUMBER=$(gh pr list --base master --head production --jq ".[] | .url" --json url | grep -oP '/pull/\K\d+')" >> "$GITHUB_ENV"
    - run: |
        gh pr merge --merge "$TARGET_PR_NUMBER" --auto
