name: Build docker image

on: 
  push:
    branches:
      - master

env:
  DOCKERHUB_REPOSITORY: ryu310/github_action_sandbox

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1.0.4
        with:
          version: v0.3.1

      - name: Build Docker Image
        run: >
          docker buildx build
          --tag ${DOCKERHUB_REPOSITORY}
          --platform linux/amd64
          --cache-from type=registry,ref=${DOCKERHUB_REPOSITORY}
          --cache-to type=registry,ref=${DOCKERHUB_REPOSITORY},mode=max
          --file ./.docker/Dockerfile .

      - name: Login to Docker Hub
        run: >
          echo ${{ secrets.DOCKER_REGISTRY_PASSWORD }} |
          docker login --username ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin

      - name: Push Docker Image
        run: >
          docker push ${DOCKERHUB_REPOSITORY}

  publish_description:
    runs-on: ubuntu-latest
    needs: build_and_push
    
    steps:
      - uses: actions/checkout@v2

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2.1.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          DOCKERHUB_REPOSITORY: ${{ env.DOCKERHUB_REPOSITORY }}
          README_FILEPATH: ./README.md
