name: Environment

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GLOBAL_ENVIRONMENT_VARIABLE: GLOBAL_ENVIRONMENT_VARIABLE

    steps:
      - run: |
          echo GLOBAL_ENVIRONMENT_VARIABLE is $GLOBAL_ENVIRONMENT_VARIABLE  # can use $STEP_ENVIRONMENT_VARIABLE
          echo STEP_ENVIRONMENT_VARIABLE is $STEP_ENVIRONMENT_VARIABLE      # can't use $STEP_ENVIRONMENT_VARIABLE
      - run: |
          echo ::set-env name=STEP_ENVIRONMENT_VARIABLE::STEP_ENVIRONMENT_VARIABLE
          echo STEP_ENVIRONMENT_VARIABLE is $STEP_ENVIRONMENT_VARIABLE      # can't use $STEP_ENVIRONMENT_VARIABLE
      - run: |
          echo STEP_ENVIRONMENT_VARIABLE is $STEP_ENVIRONMENT_VARIABLE      # can use $STEP_ENVIRONMENT_VARIABLE
