name: Environment

on:
  push:
    branches:
      - empty-match

env:
  ACTION_GLOBAL_ENVIRONMENT_VARIABLE: environment action

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JOB_GLOBAL_ENVIRONMENT_VARIABLE: build job

    steps:
      - run: |
          echo ACTION_GLOBAL_ENVIRONMENT_VARIABLE is $ACTION_GLOBAL_ENVIRONMENT_VARIABLE  # can use $ACTION_GLOBAL_ENVIRONMENT_VARIABLE
          echo JOB_GLOBAL_ENVIRONMENT_VARIABLE is $JOB_GLOBAL_ENVIRONMENT_VARIABLE        # can use $JOB_GLOBAL_ENVIRONMENT_VARIABLE
          echo STEP_ENVIRONMENT_VARIABLE is $STEP_ENVIRONMENT_VARIABLE                    # can't use $STEP_ENVIRONMENT_VARIABLE
      - run: |
          echo ::set-env name=STEP_ENVIRONMENT_VARIABLE::"step of build job"
          
          echo ACTION_GLOBAL_ENVIRONMENT_VARIABLE is $ACTION_GLOBAL_ENVIRONMENT_VARIABLE  # can use $ACTION_GLOBAL_ENVIRONMENT_VARIABLE
          echo JOB_GLOBAL_ENVIRONMENT_VARIABLE is $JOB_GLOBAL_ENVIRONMENT_VARIABLE        # can use $JOB_GLOBAL_ENVIRONMENT_VARIABLE
          echo STEP_ENVIRONMENT_VARIABLE is $STEP_ENVIRONMENT_VARIABLE                    # can't use $STEP_ENVIRONMENT_VARIABLE
      - run: |
          echo STEP_ENVIRONMENT_VARIABLE is $STEP_ENVIRONMENT_VARIABLE                    # can use $STEP_ENVIRONMENT_VARIABLE

  build2:
    runs-on: ubuntu-latest
    env:
      JOB_GLOBAL_ENVIRONMENT_VARIABLE: build2 job

    steps:
      - run: |
          echo ACTION_GLOBAL_ENVIRONMENT_VARIABLE is $ACTION_GLOBAL_ENVIRONMENT_VARIABLE  # can use $ACTION_GLOBAL_ENVIRONMENT_VARIABLE
          echo JOB_GLOBAL_ENVIRONMENT_VARIABLE is $JOB_GLOBAL_ENVIRONMENT_VARIABLE        # can use $JOB_GLOBAL_ENVIRONMENT_VARIABLE
          echo STEP_ENVIRONMENT_VARIABLE is $STEP_ENVIRONMENT_VARIABLE                    # can't use $STEP_ENVIRONMENT_VARIABLE
      - run: |
          echo ::set-env name=STEP_ENVIRONMENT_VARIABLE::"step of build2 job"
          
          echo ACTION_GLOBAL_ENVIRONMENT_VARIABLE is $ACTION_GLOBAL_ENVIRONMENT_VARIABLE  # can use $ACTION_GLOBAL_ENVIRONMENT_VARIABLE
          echo JOB_GLOBAL_ENVIRONMENT_VARIABLE is $JOB_GLOBAL_ENVIRONMENT_VARIABLE        # can use $JOB_GLOBAL_ENVIRONMENT_VARIABLE
          echo STEP_ENVIRONMENT_VARIABLE is $STEP_ENVIRONMENT_VARIABLE                    # can't use $STEP_ENVIRONMENT_VARIABLE
      - run: |
          echo STEP_ENVIRONMENT_VARIABLE is $STEP_ENVIRONMENT_VARIABLE                    # can use $STEP_ENVIRONMENT_VARIABLE
