name: Github Environment Test

on: push

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    environment: production

    steps:
    - run: echo ${{ secrets.SECRET_A }}
    - run: echo ${{ vars.TEST_A }}
