name: Github Environment Test

on: push

permissions:
  contents: read
env:
  ENV_NAME: staging

jobs:
  test:

    runs-on: ubuntu-latest
    environment: ${{ env.ENV_NAME }}

    steps:
    - run: echo ${{ secrets.SECRET_A }}
    - run: echo ${{ vars.TEST_A }}
