name: Generate github token

on:
  workflow_call:
    secrets:
      app_id:
        required: true
      private_key:
        required: true

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.app_id }}
          private_key: ${{ secrets.private_key }}
