name: Show `git diff`
on:
  workflow_dispatch:
jobs:
  check_for_changes:
    name: Check for changes
    runs-on: ubuntu-latest
    outputs:
      result_of_check_for_changes: ${{ steps.check_for_changes.outputs.result }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for changes
        id: check_for_changes
        env:
          COMMIT_FROM: origin/diff_from
          COMMIT_TO: origin/diff_to
          CHANGES_FILE: /tmp/changes_from_production_to_staging
        run: |
          set -o pipefail

          # [MEMO]
          #   * 差分があるときは step を続け、git コマンドが失敗したときは step を止めたいので `--exit-code` は使っていない
          #   * `git diff A...B` は A と B の merge-base から B までの差分を指す(`git diff $(git merge-base A B) B` と同等)
          #     * see. https://git-scm.com/docs/git-diff#Documentation/git-diff.txt-emgitdiffemltoptionsgtltcommitgtltcommitgt--ltpathgt82308203-1
          #     * 要するに、production を staging にマージすると、どういう差分が出るか？を指す
          git diff ${COMMIT_TO}...${COMMIT_FROM} | tee $CHANGES_FILE
          if test -s $CHANGES_FILE; then
            echo "result=changes_exist" >> $GITHUB_OUTPUT
          else
            echo "No need to backport"
            echo "result=no_change" >> $GITHUB_OUTPUT
          fi

  some_operations:
    name: Some operations
    runs-on: ubuntu-latest
    needs: check_for_changes
    if: needs.check_for_changes.outputs.result_of_check_for_changes == 'changes_exist'
    steps:
      - uses: actions/checkout@v4
      - name: echo
        run: echo backport
