name: Show `git diff`
on:
  workflow_dispatch:
jobs:
  check_for_changes:
    name: Check for changes
    runs-on: ubuntu-latest
    outputs:
      is_needed: ${{ steps.check_for_changes.outputs.result == 1 }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for changes
        id: check_for_changes
        run: |
          set -o pipefail
          CHANGES_FILE=/tmp/changes_from_diff_from_to_diff_to

          # 差分があるときは step を続け、git コマンドが失敗したときは step を止めたいので `--exit-code` は使っていない
          git diff origin/diff_to...origin/diff_from | tee $CHANGES_FILE
          echo "result=$(test -s $CHANGES_FILE || $?)" >> $GITHUB_OUTPUT

  some_operations:
    name: Some operations
    runs-on: ubuntu-latest
    needs: check_for_changes
    if: needs.check_for_changes.outputs.is_needed
    steps:
      - uses: actions/checkout@v4
      - name: echo
        run: echo backport
