name: ruby script test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3
      - run: |
          ruby -e '
            require "yaml"
            target_dependency_name = ARGV.first
            config = open(".github/auto-merge-list.yaml", 'r') { |f| YAML.load(f) }
            puts config
          '
