name: workflow telemetry action
on: push
permissions:
  actions: read
  pull-requests: write
jobs:
  workflow-telemetry-action:
    runs-on: ubuntu-latest
    steps:
      # - name: Collect Workflow Telemetry
      #   uses: catchpoint/workflow-telemetry-action@v2
      - name: Collect Workflow Telemetry
        uses: ./.github/actions/workflow-telemetry-action
